<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.dao.support.DataAccessUtilsTests" tests="10" skipped="0" failures="0" errors="0" timestamp="2020-12-11T19:53:24" hostname="DESKTOP-TMNPDT1" time="0.068">
  <properties/>
  <testcase name="withString()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.012"/>
  <testcase name="withInteger()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.006"/>
  <testcase name="exceptionTranslationWithNoTranslation()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.001"/>
  <testcase name="withDate()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.018"/>
  <testcase name="withLong()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.001"/>
  <testcase name="withTooLargeCollection()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.005"/>
  <testcase name="withSameIntegerInstanceTwice()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.001"/>
  <testcase name="withEmptyCollection()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.003"/>
  <testcase name="withEquivalentIntegerInstanceTwice()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.003"/>
  <testcase name="exceptionTranslationWithTranslation()" classname="org.springframework.dao.support.DataAccessUtilsTests" time="0.002"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
